/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.7.1.502 */
/* Module Version: 5.4 */
/* Fri Jun 17 20:21:10 2016 */

/* parameterized module instance */
BOOTROM1 __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), .Q( ));
