-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.9.1.119
-- Module  Version: 5.7
-- Mon Aug 21 18:35:52 2017

-- parameterized module component declaration
component C64_Clock
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic; CLKOS2: out  std_logic; 
        CLKOS3: out  std_logic; LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : C64_Clock
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__, CLKOS2=>__, CLKOS3=>__, 
        LOCK=>__);
