-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.9.1.119
-- Module  Version: 5.7
-- Mon Aug 21 18:35:42 2017

-- parameterized module component declaration
component DVI_PLL
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic; CLKOS2: out  std_logic);
end component;

-- parameterized module component instance
__ : DVI_PLL
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__, CLKOS2=>__);
